use std::str::FromStr;

#[derive(Debug, Hash, Eq, PartialEq)]
pub enum TrackName {
    Meta,
    Events,
    Beat,
    Venue,
    Guitar,
    Gh1Guitar,
    GuitarCoop,
    Bass,
    Rhythm,
    Keys,
    ProGuitar17Fret,
    ProGuitar22Fret,
    ProBass17Fret,
    ProBass22Fret,
    Drums,
    Drums2,
    DrumsReal,
    GhlGuitar,
    GhlBass,
    GhlRhythm,
    GhlGuitarCoop,
    Vocals,
    Harmony1,
    Harmony2,
    Harmony3,
    Harmony1_2,
    Harmony2_2,
    Harmony3_2,
    ProKeysExpert,
    ProKeysHard,
    ProKeysMedium,
    ProKeysEasy,
}

impl FromStr for TrackName {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "BEAT" => Ok(TrackName::Beat),
            "EVENTS" => Ok(TrackName::Events),
            "VENUE" => Ok(TrackName::Venue),
            "PART GUITAR" => Ok(TrackName::Guitar),
            "T1 GEMS" => Ok(TrackName::Gh1Guitar),
            "PART GUITAR COOP" => Ok(TrackName::GuitarCoop),
            "PART BASS" => Ok(TrackName::Bass),
            "PART RHYTHM" => Ok(TrackName::Rhythm),
            "PART KEYS" => Ok(TrackName::Keys),
            "PART REAL_GUITAR" => Ok(TrackName::ProGuitar17Fret),
            "PART REAL_GUITAR_22" => Ok(TrackName::ProGuitar22Fret),
            "PART REAL_BASS" => Ok(TrackName::ProBass17Fret),
            "PART REAL_BASS_22" => Ok(TrackName::ProBass22Fret),
            "PART DRUMS" => Ok(TrackName::Drums),
            "PART DRUM" => Ok(TrackName::Drums2),
            "PART REAL_DRUMS_PS" => Ok(TrackName::DrumsReal),
            "PART GUITAR GHL" => Ok(TrackName::GhlGuitar),
            "PART BASS GHL" => Ok(TrackName::GhlBass),
            "PART RHYTHM GHL" => Ok(TrackName::GhlRhythm),
            "PART GUITAR COOP GHL" => Ok(TrackName::GhlGuitarCoop),
            "PART VOCALS" => Ok(TrackName::Vocals),
            "HARM1" => Ok(TrackName::Harmony1),
            "HARM2" => Ok(TrackName::Harmony2),
            "HARM3" => Ok(TrackName::Harmony3),
            "PART HARM1" => Ok(TrackName::Harmony1_2),
            "PART HARM2" => Ok(TrackName::Harmony2_2),
            "PART HARM3" => Ok(TrackName::Harmony3_2),
            "PART REAL_KEYS_X" => Ok(TrackName::ProKeysExpert),
            "PART REAL_KEYS_H" => Ok(TrackName::ProKeysHard),
            "PART REAL_KEYS_M" => Ok(TrackName::ProKeysMedium),
            "PART REAL_KEYS_E" => Ok(TrackName::ProKeysEasy),
            "" => Ok(TrackName::Meta),
            _ => Err("Not found".parse().unwrap_err()),
        }
    }
}
